service: marvel-api

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    MARVEL_API_URL: http://gateway.marvel.com/v1/public
    MARVEL_PRIVATE_KEY: ${ssm:marvel-private-key~true}
    MARVEL_PUBLIC_KEY: ${ssm:marvel-public-key~true}

plugins:
  - serverless-offline

functions:
  get-heroes-by-movies:
    handler: heroes/controllers/get-heroes-by-movies.handler
    events:
      - http:
          path: /heroes/movies
          method: get
  get-heroes:
    handler: heroes/controllers/get-heroes.handler
    events:
      - http:
          path: /heroes
          method: get
  get-hero:
    handler: heroes/controllers/get-hero.handler
    events:
      - http:
          path: /hero/{id}
          method: get
